### ISSUE TITLE
tex to pdf dont work

### ISSUE THREAD

**Issue by uev** [sherif181/java-sequence-diagram-generator#1]
pdflatex  test.AnnotationTest.captionTest.tex
This is pdfTeX, Version 3.1415926-1.40.10 (TeX Live 2009/Debian)
entering extended mode
(./test.AnnotationTest.captionTest.tex
LaTeX2e <2009/09/24>
Babel <v3.8l> and hyphenation patterns for english, usenglishmax, dumylang, noh
yphenation, loaded.

! LaTeX Error: Environment figure undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.1  \begin{figure}

**Comment by sherif181** [comment]
it cant recognize \begin{figure} which is  a basic latex command  i guess it is not a direct error of the generator  just a configuration error can you send me all your latex files ?

**Comment by uev** [comment]
It's generated:

 \begin{figure}
 \begin{center}
 \begin{sequencediagram}
\newthread{testAnnotationTest}{AnnotationTest}
\newinst{testController}{Controller}
\newinst{testModel}{Model}
\begin{call}{testAnnotationTest}{init}{testController}{void 0ms}
\begin{call}{testController}{newInstance}{testBean}{Bean 0ms}
\end{call}
\begin{call}{testController}{setBean}{testModel}{void 0ms}
\end{call}
\begin{call}{testController}{persist}{testModel}{boolean 0ms}
\begin{call}{testModel}{persist}{testPersistor}{void 0ms}
\end{call}
\end{call}
\end{call}
\begin{call}{testAnnotationTest}{simpleBeanOperation}{testController}{void 0ms}
\begin{call}{testController}{getBean}{testModel}{Bean 0ms}
\end{call}
\begin{call}{testController}{simpleBeanOperation}{testBean}{void 0ms}
\end{call}
\begin{call}{testController}{setBean}{testModel}{void 0ms}
\end{call}
\begin{call}{testController}{persist}{testModel}{boolean 0ms}
\begin{call}{testModel}{persist}{testPersistor}{void 0ms}
\end{call}
\end{call}
\end{call}
 \end{sequencediagram}
\caption{CAPTION}
\label{test.AnnotationTest.captionTest}
\end{center}
\end{figure}

**Comment by sherif181** [comment]
Looks ok 
This file is intended to be included into a  latex document.  take a look here http://latex-project.org/intro.html

You can make it work  ich you change the file in the following way 
\documentclass{article}
\title{Example}

\begin{document}
\begin{figure}
 \begin{center}
 \begin{sequencediagram}
 \newthread{testAnnotationTest}{AnnotationTest}
 \newinst{testController}{Controller}
 \newinst{testModel}{Model}
 \begin{call}{testAnnotationTest}{init}{testController}{void 0ms}
 \begin{call}{testController}{newInstance}{testBean}{Bean 0ms}
 \end{call}
 \begin{call}{testController}{setBean}{testModel}{void 0ms}
 \end{call}
 \begin{call}{testController}{persist}{testModel}{boolean 0ms}
 \begin{call}{testModel}{persist}{testPersistor}{void 0ms}
 \end{call}
 \end{call}
 \end{call}
 \begin{call}{testAnnotationTest}{simpleBeanOperation}{testController}{void 0ms}
 \begin{call}{testController}{getBean}{testModel}{Bean 0ms}
 \end{call}
 \begin{call}{testController}{simpleBeanOperation}{testBean}{void 0ms}
 \end{call}
 \begin{call}{testController}{setBean}{testModel}{void 0ms}
 \end{call}
 \begin{call}{testController}{persist}{testModel}{boolean 0ms}
 \begin{call}{testModel}{persist}{testPersistor}{void 0ms}
 \end{call}
 \end{call}
 \end{call}
 \end{sequencediagram}
 \caption{CAPTION}
 \label{test.AnnotationTest.captionTest}
 \end{center}
 \end{figure}
\end{document}
